### ISSUE TITLE
Stuck at Downloading assets for windows

### ISSUE THREAD

**Issue by gliheng** [dhairy-online/flappybird#3]
Hi, after I compile this on windows and run it. I got following error:

```
Downloading assets for windows
error: TypeError: Release asset for windows not found.
    at downloadRelease (file://$deno$/bundle.js:402:19)
    at async init (file://$deno$/bundle.js:423:5)
    at async Canvas.[Symbol.asyncIterator] (file://$deno$/bundle.js:343:22)
    at async file://$deno$/bundle.js:571:18
```

**Comment by sebjoub** [comment]
You will probably have to adapt this answer for windows but on linux I had to do a couple of manual operations to have a fresh version of deno_sdl2 and make the whole thing work because the deno_sdl2 referenced in the project doesn't seem to work anymore so I complied it locally and then used it in flappybird:

installed deno_sdl2 (git-clone the repo) but also installed these:
sudo apt-get install libasound2-dev
sudo apt-get install libsdl2-dev
sudo apt-get install libsdl2-ttf-dev
sudo apt-get install libsdl2-image-dev

then followed instructions for deno_sdl2:
deno install -Afq -n deno_bindgen https://raw.githubusercontent.com/littledivy/deno_bindgen/main/cli.ts
cargo install cargo-vcpkg
cargo vcpkg -v build

also had to remove the arguments: "-- --features "use_vcpkg""
so just running this command
deno_bindgen

Then is flappybird directory:
Replaced this line
import { Canvas } from "https://deno.land/x/sdl2@0.1-alpha.6/src/canvas.ts";
to:
import { Canvas } from "../deno_sdl2/mod.ts";

Then run flappybird:
deno run --allow-all --unstable  main.js
